version: '3'

services:
  app:
    stdin_open: true
    tty: true
    build: .
    command: 
      - "/bin/bash"
      - "-l"
      - "-c"
      - "npm install && bash"
    volumes:
      - ./:/src/
      - /src/node_modules
    networks:
      - eth-todo-list
  ganache:
    image: trufflesuite/ganache-cli:v6.12.2
    networks:
      - eth-todo-list
networks:
  eth-todo-list:
    driver: bridge
